// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(PersonalContext))]
    [Migration("20240409042615_Newe")]
    partial class Newe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.PersonalEntity", b =>
                {
                    b.Property<double?>("ID")
                        .HasColumnType("float");

                    b.Property<string>("CARGO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("CELULAR")
                        .HasColumnType("float");

                    b.Property<string>("COORDINADOR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CORREO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPERSONAL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUMPLEAÑOS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEPARTAMENTO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("DIAS_AL_CESE")
                        .HasColumnType("float");

                    b.Property<double?>("DIAS_EMPRESA")
                        .HasColumnType("float");

                    b.Property<string>("DIRECCION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISTRITO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DNI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMPRESA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Equipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("F31")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FECHA_CESE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FECHA_PROYECTO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FUNCION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GABIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("INGRESO_INDRA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MODALIDAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OBSERVACION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PEOPLE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PERIODO_PRUEBA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PERSONAL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROVINCIA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PUESTO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ROL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TASA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VACACIONES_URGENTES")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TBPersonal");
                });
#pragma warning restore 612, 618
        }
    }
}
